---
deployment:
  tasks:
    - export COREPATH=/home/rdhd8957/inventory
    - export PUBLICPATH=/home/rdhd8957/public_html
    
    # 1. Create core folder if it doesn't exist
    - /bin/mkdir -p $COREPATH
    
    # 2. Sync Core Files (excluding public folder and git files)
    # We INCLUDE vendor here because the user is pushing it to Git
    - /usr/bin/rsync -av --delete --exclude='.git*' --exclude='node_modules' --exclude='/public' --exclude='storage/logs/*' . $COREPATH
    
    # 3. Sync Public Files to public_html and patch index.php paths
    - /usr/bin/rsync -av --delete public/ $PUBLICPATH
    - /bin/sed -i "s|require __DIR__.'/../vendor/autoload.php'|require __DIR__.'/../inventory/vendor/autoload.php'|g" $PUBLICPATH/index.php
    - /bin/sed -i "s|require_once __DIR__.'/../bootstrap/app.php'|require_once __DIR__.'/../inventory/bootstrap/app.php'|g" $PUBLICPATH/index.php
    
    # 4. Copy production environment
    - if [ -f $COREPATH/.env.hosting ]; then /bin/cp $COREPATH/.env.hosting $COREPATH/.env; fi
    
    # 5. Run Laravel optimization (skip composer install as user has no SSH/CLI support for it)
    - if [ -f $COREPATH/artisan ]; then php $COREPATH/artisan storage:link --force; fi
    - if [ -f $COREPATH/vendor/autoload.php ]; then php $COREPATH/artisan optimize; fi
    
    # 6. Correct Permissions
    - /bin/chmod -R 775 $COREPATH/storage $COREPATH/bootstrap/cache
    - /bin/chmod 600 $COREPATH/.env
