<?php

namespace App\Http\Controllers;

use App\Models\InventoryItem;
use App\Models\InventoryUnit;
use App\Helpers\ImageHelper;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class InventoryUnitController extends Controller
{
    use AuthorizesRequests;

    /**
     * Show scan barcode page
     */
    public function scanPage()
    {
        return view('inventory_units.scan');
    }

    /**
     * Process scanned barcode and redirect to unit detail
     */
    public function processScan(Request $request)
    {
        $request->validate([
            'barcode' => 'required|string',
        ]);

        $barcode = trim($request->input('barcode'));

        // Search by ID with eager loading of inventory item
        $unit = InventoryUnit::with('item')->find($barcode);

        if (!$unit) {
            \Illuminate\Support\Facades\Log::warning('Unit not found on scan', ['barcode' => $barcode]);
            return redirect()
                ->route('units.scan')
                ->with('error', 'Unit dengan ID "' . $barcode . '" tidak ditemukan');
        }

        // Check authorization
        try {
            $this->authorize('view', $unit);
        } catch (\Illuminate\Auth\Access\AuthorizationException $e) {
            return redirect()
                ->route('units.scan')
                ->with('error', 'Anda tidak memiliki akses untuk melihat unit ini');
        }

        // Get the inventory item
        $inventory = $unit->item;

        if (!$inventory) {
            \Illuminate\Support\Facades\Log::error('Unit has no related inventory item', [
                'unit_id' => $unit->id,
                'inventory_item_id' => $unit->inventory_item_id,
            ]);
            return redirect()
                ->route('units.scan')
                ->with('error', 'Data integritas rusak: Unit #' . $unit->id . ' tidak terhubung ke inventaris apapun');
        }

        \Illuminate\Support\Facades\Log::info('Unit scanned successfully', [
            'unit_id' => $unit->id,
            'inventory_id' => $inventory->id,
        ]);

        return redirect()
            ->route('inventories.units.show', [$inventory->id, $unit->id])
            ->with('success', 'Unit ditemukan! 📦');
    }

    public function create(InventoryItem $inventory)
    {
        $this->authorize('create', InventoryUnit::class);

        return view('inventory_units.create', compact('inventory'));
    }

    public function store(Request $request, InventoryItem $inventory)
    {
        $this->authorize('create', InventoryUnit::class);

        $data = $request->validate([
            'serial_number'    => 'nullable|string|max:255|unique:inventory_units,serial_number',
            'photo'            => 'nullable|image|max:2048',
            'condition_status' => 'required|in:available,in_use,maintenance,damaged,lost',
            'current_holder'   => 'required|string|max:255',
            'note'             => 'nullable|string|max:500',
        ]);

        if ($request->hasFile('photo')) {
            $data['photo'] = ImageHelper::upload(
                $request->file('photo'),
                'unit_photos'
            );
        }

        // QR code will be automatically generated by the InventoryUnit model's booted() hook
        $inventory->units()->create($data);

        return redirect()
            ->route('inventories.show', $inventory)
            ->with('success', 'Unit berhasil ditambahkan! QR code sudah di-generate otomatis.');
    }

    public function update(Request $request, InventoryItem $inventory, string $unitId)
    {

        $unit = $inventory->units()->findOrFail($unitId);
        $this->authorize('update', $unit);

        $data = $request->validate([
            'serial_number'    => 'nullable|string|max:255|unique:inventory_units,serial_number,' . $unitId . ',id',
            'photo'            => 'nullable|image|max:2048',
            'condition_status' => 'required|in:available,in_use,maintenance,damaged,lost',
            'current_holder'   => 'required|string|max:255',
            'note'             => 'nullable|string|max:500',
        ]);

        if ($request->hasFile('photo')) {
            ImageHelper::delete($unit->photo);

            $data['photo'] = ImageHelper::upload(
                $request->file('photo'),
                'unit_photos'
            );
        }

        $unit->update($data);

        return redirect()
            ->route('inventories.show', $inventory)
            ->with('success', 'Unit berhasil diperbarui!');
    }

    public function destroy(InventoryItem $inventory, string $unitId)
    {
        // Cari manual
        $unit = $inventory->units()->findOrFail($unitId);

        $this->authorize('delete', $unit);

        ImageHelper::delete($unit->photo);
        $unit->delete();

        return redirect()
            ->route('inventories.show', $inventory)
            ->with('success', 'Unit berhasil dihapus');
    }

    public function show(InventoryItem $inventory, string $unitId)
    {
        // Cari unit SECARA MANUAL melalui relasi inventory agar foreign key 'inventory_item_id' terbaca
        $unit = $inventory->units()->findOrFail($unitId);

        $this->authorize('view', $unit);

        // Baris ini sebenarnya sudah tidak perlu karena findOrFail di atas sudah memastikan unit milik inventory tersebut
        // abort_if($unit->inventory_item_id !== $inventory->id, 404);

        return view('inventory_units.show', compact('inventory', 'unit'));
    }

    public function edit(InventoryItem $inventory, string $unitId)
    {
        // 1. Cari unit
        $unit = $inventory->units()->findOrFail($unitId);

        // 2. Otorisasi
        $this->authorize('update', $unit);

        // 3. --- TAMBAHAN PENTING ---
        // Definisikan daftar status yang bisa dipilih.
        // Sesuaikan isi array ini dengan kebutuhan aplikasimu (misal: 'available', 'damaged', 'maintenance', dll)
        $conditionStatuses = ['available', 'in_use', 'maintenance', 'damaged', 'lost'];

        // 4. Kirim variabel $conditionStatuses ke view menggunakan compact
        return view('inventory_units.edit', compact('inventory', 'unit', 'conditionStatuses'));
    }
}
